import { describe, expect, it } from "bun:test";

import {
  isStandardUuid,
  shortToUuid,
  toShortUuid,
  toStandardUuid,
  uuidToShort,
} from "./short-uuid.ts";

describe("short-uuid", () => {
  describe("round-trip conversion", () => {
    it("converts a UUID to short and back", () => {
      const uuid = "a44521d0-0fb8-4ade-8002-3385545c3318";
      const short = uuidToShort(uuid);
      expect(short).toHaveLength(22);
      expect(shortToUuid(short)).toBe(uuid);
    });

    it("handles zero UUID", () => {
      const uuid = "00000000-0000-0000-0000-000000000000";
      const short = uuidToShort(uuid);
      expect(short).toHaveLength(22);
      expect(short).toBe("2222222222222222222222");
      expect(shortToUuid(short)).toBe(uuid);
    });

    it("handles max UUID", () => {
      const uuid = "ffffffff-ffff-ffff-ffff-ffffffffffff";
      const short = uuidToShort(uuid);
      expect(short).toHaveLength(22);
      expect(shortToUuid(short)).toBe(uuid);
    });

    it("round-trips multiple random UUIDs", () => {
      for (let i = 0; i < 20; i++) {
        const uuid = crypto.randomUUID();
        const short = uuidToShort(uuid);
        expect(short).toHaveLength(22);
        expect(shortToUuid(short)).toBe(uuid);
      }
    });
  });

  describe("Python shortuuid compatibility", () => {
    // Known pairs generated by Python shortuuid library
    it("matches Python shortuuid output", () => {
      const pairs: [string, string][] = [
        ["00000000-0000-0000-0000-000000000000", "2222222222222222222222"],
        ["00000000-0000-0000-0000-000000000001", "2222222222222222222223"],
        ["0684c425-6801-4bdb-ac83-3b828a2ea438", "3B8Cp8TXzdNWdUvCMkRqzm"],
      ];
      for (const [uuid, expectedShort] of pairs) {
        expect(uuidToShort(uuid)).toBe(expectedShort);
        expect(shortToUuid(expectedShort)).toBe(uuid);
      }
    });
  });

  describe("idempotency", () => {
    it("toShortUuid is idempotent", () => {
      const uuid = "a44521d0-0fb8-4ade-8002-3385545c3318";
      const short = toShortUuid(uuid);
      expect(toShortUuid(short)).toBe(short);
    });

    it("toStandardUuid is idempotent", () => {
      const uuid = "a44521d0-0fb8-4ade-8002-3385545c3318";
      const standard = toStandardUuid(uuid);
      expect(toStandardUuid(standard)).toBe(standard);
    });
  });

  describe("format detection", () => {
    it("detects standard UUID format", () => {
      expect(isStandardUuid("a44521d0-0fb8-4ade-8002-3385545c3318")).toBe(true);
      expect(isStandardUuid("keATfhavoPWVIVaNE8xbmj")).toBe(false);
      expect(isStandardUuid("not-a-uuid")).toBe(false);
    });

    it("toStandardUuid accepts both formats", () => {
      const uuid = "a44521d0-0fb8-4ade-8002-3385545c3318";
      const short = uuidToShort(uuid);
      expect(toStandardUuid(uuid)).toBe(uuid);
      expect(toStandardUuid(short)).toBe(uuid);
    });

    it("toShortUuid accepts both formats", () => {
      const uuid = "a44521d0-0fb8-4ade-8002-3385545c3318";
      const short = uuidToShort(uuid);
      expect(toShortUuid(uuid)).toBe(short);
      expect(toShortUuid(short)).toBe(short);
    });
  });

  describe("short UUID character set", () => {
    it("only contains valid Base57 characters", () => {
      const validChars = /^[2-9A-HJ-NP-Za-km-z]+$/;
      for (let i = 0; i < 50; i++) {
        const short = uuidToShort(crypto.randomUUID());
        expect(short).toMatch(validChars);
      }
    });
  });

  describe("uppercase UUID normalization", () => {
    it("toStandardUuid lowercases standard UUIDs", () => {
      const upper = "A44521D0-0FB8-4ADE-8002-3385545C3318";
      expect(toStandardUuid(upper)).toBe("a44521d0-0fb8-4ade-8002-3385545c3318");
    });
  });
});
