// scripts/generate-public-manifest.ts
// Scans public/ and generates src/_public-files.ts with { type: "file" } imports
// so static files work in both dev mode and compiled Bun executables.

const publicDir = "./public";
const outFile = "./src/_public-files.ts";

const glob = new Bun.Glob("**/*");
const files: string[] = [];

for await (const path of glob.scan({ cwd: publicDir, onlyFiles: true })) {
  files.push(path);
}

files.sort();

const lines: string[] = ["// Auto-generated by scripts/generate-public-manifest.ts — do not edit"];

for (let i = 0; i < files.length; i++) {
  lines.push(`import f${i} from "../public/${files[i]}" with { type: "file" };`);
}

lines.push("");
lines.push("export const publicFiles: Record<string, string> = {");
for (let i = 0; i < files.length; i++) {
  lines.push(`  "/${files[i]}": f${i},`);
}
lines.push("};");
lines.push("");

await Bun.write(outFile, lines.join("\n"));
console.log(`Generated ${outFile} with ${files.length} file(s)`);
